name = "0pesadelo-web-vtt"
account_id = "843f1ea5032724a4b74ad6ccd6bfab30"
main = "src/index.js"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

# Configuração do Banco Relacional Cloudflare D1
[[d1_databases]]
binding = "DB"
database_name = "arcana_vtt_db"
database_id = "0c182dd7-36f9-45cf-a3bd-bfa8a639ee4d"
migrations_dir = "migrations"

# Variáveis e Segredos de Ambiente
[vars]
ENVIRONMENT = "development"
ALLOWED_ORIGINS = "http://localhost:5500,http://127.0.0.1:5500,https://0pesadelo-frontend.trevorrot.workers.dev"
JWT_SECRET = "arcana-super-secret-key-development-local-2026-vtt"
FRONTEND_URL = "https://0pesadelo-frontend.trevorrot.workers.dev"

# NOTA: O GOOGLE_CLIENT_ID e o GOOGLE_CLIENT_SECRET não devem ficar aqui pois ficam expostos no GitHub!
# Eles devem ser adicionados na Cloudflare usando os comandos de terminal:
# npx wrangler secret put GOOGLE_CLIENT_ID
# npx wrangler secret put GOOGLE_CLIENT_SECRET
